- name: Create ~/.local/bin
  file:
    path: /home/{{ user_name }}/.local/bin
    state: directory

- name: Download kas-container
  get_url:
    url: https://raw.githubusercontent.com/siemens/kas/2.6.3/kas-container
    dest: /home/{{ user_name }}/.local/bin/kas-container
    mode: "0775"
