- name: Download Rust installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: "0775"

- name: Install Rust
  shell: /tmp/rustup.sh -y

- name: Remove Rust installer
  file:
    path: /tmp/rustup.sh
    state: absent
